mye956/amazon-ecs-agent

build-infrastructure/test-pipeline.yml
buildspecs/test-buildspec.yml

Added build-infrastructure and buildspec

---

build-infrastructure/test-pipeline.yml
buildspecs/test-buildspec.yml

* Added build-infrastructure and buildspec
* Commented out aws s3 cp command in test-buildspec.yml
---------

Added build-infrastructure and buildspec (#3)

---

build-infrastructure/codebuild-devbuild-stack.yml
build-infrastructure/release-pipeline-stack.yml
build-infrastructure/test-codebuild-dev-stack.yml
build-infrastructure/test-pipeline.yml
buildspecs/copy.yml
buildspecs/pr-build-ubuntu.yml
buildspecs/pr-build.yml
buildspecs/release-config.yml
buildspecs/signing.yml
buildspecs/test-buildspec.yml

Kicking off copy of All Dog Codepipeline in personal dev account

---

build-infrastructure/codebuild-devbuild-stack.yml
build-infrastructure/release-pipeline-stack.yml
build-infrastructure/test-codebuild-dev-stack.yml
build-infrastructure/test-pipeline.yml
buildspecs/copy.yml
buildspecs/pr-build-ubuntu.yml
buildspecs/pr-build.yml
buildspecs/release-config.yml
buildspecs/signing.yml
buildspecs/test-buildspec.yml

Added back missing ending quote

---

build-infrastructure/al1-codebuild-stack.yml
buildspecs/test-buildspec.yml

Added al1 codebuild stack and modified test-buildspec

---

buildspecs/test-buildspec.yml

Uncommenting out the rest of the code in test-buildspec.yml

---

buildspecs/test-buildspec.yml

Getting full commit sha

---

buildspecs/test-buildspec.yml

fixed git parse command

---

buildspecs/test-buildspec.yml

Added agent.json for AL1

---

buildspecs/test-buildspec.yml

Cleaned up buildspec.yml file

---

buildspecs/test-buildspec.yml

Added check if there's no new agent release version in buildspec

---

buildspecs/test-buildspec.yml

Changed exit code to 1

---

buildspecs/test-buildspec.yml

Added comments

---

buildspecs/test-buildspec.yml

Made comment clearer

---

build-infrastructure/test-pipeline.yml
buildspecs/test-buildspec.yml

Added GITHUB_SOURCE_BRANCH_NAME as env

---

buildspecs/test-buildspec.yml

Fixed to yum update

---

buildspecs/test-buildspec.yml

Debugging pre_build

---

buildspecs/test-buildspec.yml

Debugging buildspec

---

scripts/al1-release-config.sh

Outputting release config files

---

scripts/al1-release-config.sh

Debugging release script

---

buildspecs/al1-release-config.sh
scripts/al1-release-config.sh

Al1 patch dummy

---

scripts/al1-release-config.sh

Removed previous update command
